# Generated by Django 4.0 on 2021-12-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
    ]
